### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by pawandeep2155** [lsegal/my_toy_compiler#32]
Hello,
I tried to compile using command `g++ -o parser llvm-config --libs core jit native --cxxflags --ldflags *.cpp` .But I am getting the following error with LLVM 3.6.2

```
./node.h:3:10: fatal error: 'llvm/IR/Value.h' file not found
#include <llvm/IR/Value.h>
         ^
1 error generated.
In file included from corefn.cpp:2:
./codegen.h:3:10: fatal error: 'llvm/IR/Module.h' file not found
#include <llvm/IR/Module.h>
```

Can you please tell me how to resolve this issue??

**Comment by lsegal** [comment]
Based on the "file not found" errors, I would guess that you do not have LLVM installed, or not correctly installed, anyway. Note that the repository is built against LLVM 3.7, not 3.6.2, so that may be relevant.

Unfortunately this project does not offer support on installing LLVM for various platforms / environments. To fix this error, you will have to look up how to correctly install and compile programs with LLVM on your system.
